/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controlefinanceiro.VIEW;

/**
 *
 * @author Ledilson
 */
public class InternalBuscaDiarioFinanceiroMensal extends javax.swing.JInternalFrame {

    /**
     * Creates new form InternalBuscaLivroCaixaMes
     */
    public InternalBuscaDiarioFinanceiroMensal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbFinanceiroMensal = new javax.swing.JTable();
        btNovaPesquisa = new javax.swing.JButton();
        jDataInicial = new com.toedter.calendar.JDateChooser();
        jDataFinal = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btProcurarRegistro = new javax.swing.JButton();
        btImprimir = new javax.swing.JButton();
        btExcel = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Diário Financeiro Mensal");

        tbFinanceiroMensal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data hora", "Descrição", "Entrada", "R$", "Data Entrada", "Saida", "R$", "Data Saida"
            }
        ));
        jScrollPane1.setViewportView(tbFinanceiroMensal);

        btNovaPesquisa.setText("Nova Pesquisa");

        jLabel1.setText("Data inicial");

        jLabel2.setText("Data Final");

        btProcurarRegistro.setText("Procurar Registro");

        btImprimir.setText("Imprimir");

        btExcel.setText("Emitir Excel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btNovaPesquisa)
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1)
                        .addGap(21, 21, 21)
                        .addComponent(jDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jLabel2)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(btProcurarRegistro)
                        .addGap(16, 16, 16)
                        .addComponent(btImprimir)
                        .addGap(18, 18, 18)
                        .addComponent(btExcel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btNovaPesquisa)
                        .addComponent(btProcurarRegistro)
                        .addComponent(btImprimir)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(btExcel))
                    .addComponent(jDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btExcel;
    private javax.swing.JButton btImprimir;
    private javax.swing.JButton btNovaPesquisa;
    private javax.swing.JButton btProcurarRegistro;
    private com.toedter.calendar.JDateChooser jDataFinal;
    private com.toedter.calendar.JDateChooser jDataInicial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbFinanceiroMensal;
    // End of variables declaration//GEN-END:variables
}
